Feature/tcin 60
hastega/Loki pull request #4
Opened 2022-12-01 16:29 UTC by GTerigiHastega

Caching of POST, PUT and PATCH requests implemented. Need to refactor common code and further expand each and every method.

2022-12-09 08:58 UTC, pablomichelettii requested changes
that's nice! GG. For the next tasks remember to update the version of Loki (@Zenomante @GTerigiHastega )

2022-12-09 08:58 UTC, pablomichelettii commented on src/app.ts
> +// Manager
Don't use repetitve comments. If u use self explanatory naming convention, as u have done, is enough

2022-12-09 08:58 UTC, pablomichelettii commented on src/app.ts
> +const swaggerDocument = require('./swagger-output.json');
I suppose the problem is that u're trying to use a json importing it as a module. If not let's discuss what is the problem @Zenomante

2022-12-09 08:58 UTC, pablomichelettii commented on src/app.ts
> +    console.log('development', `RejectUnauthorized is disabled.`);
could we make this log dynamic?

2022-12-09 08:58 UTC, pablomichelettii commented on src/controllers/localCache.controller.ts
> +        console.log(currentFile);
remove log

2022-12-09 08:58 UTC, pablomichelettii commented on src/controllers/localCache.controller.ts
> +    console.log(successResponseBody);
remove console log

2022-12-30 14:43 UTC, GTerigiHastega commented
Logging utility added. Increased version to 1.0.01

2023-01-27 08:48 UTC, pablomichelettii commented on package.json
> +  "version": "1.0.01",
don`t use 0 before the number, 1.0.1 it's ok

2023-01-27 09:03 UTC, pablomichelettii reviewed
GGWD

2023-01-27 09:03 UTC, pablomichelettii commented on package.json
> +    "npmlog": "^7.0.1",
you can remove it if u use wiston

2023-01-27 09:03 UTC, pablomichelettii commented on src/app.ts
> +// To discuss
Choose a common tag for those comments: for example i'm pretty sure there are some vscode extensions that recognize tags like //TODO: or //@TODO: just chose one so we can start to use one of those tags

2023-01-27 09:03 UTC, pablomichelettii commented on src/server.ts
> +    // console.log('Server on port', app.get('port'));
duplicate

2023-07-21 07:05 UTC, pablomichelettii reviewed
LGTM

2023-07-21 07:07 UTC, merged